# Site settings
title: Radu Szasz
email: radu.szasz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal webpage of Radu Szasz
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://raduszasz.git.io" # the base hostname & protocol for your site
twitter_username: RaduSzasz
github_username:  RaduSzasz

# Build settings
markdown: kramdown
